# Generated by Django 4.0.3 on 2022-03-31 02:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id_fruit', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_fruit', models.CharField(max_length=255)),
            ],
        ),
    ]
