# Generated by Django 4.0.3 on 2022-03-31 03:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fruit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_region', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='fruit',
            name='name_region',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='fruit.region'),
            preserve_default=False,
        ),
    ]
