# Generated by Django 4.0.3 on 2022-03-31 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fruit', '0002_region_fruit_name_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fruit',
            name='name_region',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
